name = "misub"
compatibility_date = "2026-05-20"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "MISUB_KV"
id = "0ffccaae85ed4782b8cd6b59a4557cdd"

[[d1_databases]]
binding = "MISUB_DB"
database_name = "misub-db"
database_id = "ef02e828-57ca-4528-902a-7b8fa5da44ef"
